version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: adtech-pg
    environment:
      POSTGRES_USER: antifraud
      POSTGRES_PASSWORD: antifraud123
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./deployments/init-db.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pg_data: