
upstream core_engine {
    server engine:8080;
}


server {
    listen 9090;
    server_name localhost;

location = / {
    root /usr/share/nginx/html;
    try_files /index.html =404;
}

    location /v1/challenge {
        proxy_pass http://core_engine/v1/challenge;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /click {
        proxy_pass http://core_engine/v1/click;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /bot/click {
        proxy_pass http://core_engine/v1/click;
        proxy_method POST;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header User-Agent "python-requests/2.28 (automated testing signature)";
        proxy_set_header X-Click-Source "automated";
    }
}